// SDK 3/7 (STO-616): generate src/generated/openapi.ts from the committed
// contract/openapi.json (exported by the backend's scripts/export_openapi).
//
//   pnpm --filter @bstockwelldev/agent-graph-sdk run generate [--check]
//
// `--check` exits non-zero when the committed output is stale; the SDK's
// vitest runs the same comparison (src/contract.test.ts), so CI fails on drift.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const contractUrl = new URL("../contract/openapi.json", import.meta.url);
const outputUrl = new URL("../src/generated/openapi.ts", import.meta.url);

export async function renderGenerated() {
  const document = JSON.parse(readFileSync(contractUrl, "utf8"));
  // defaultNonNullable: false -- a field with a server default is optional to
  // send (request bodies); the SDK's Zod schemas stay the authority on what
  // responses actually contain.
  const ast = await openapiTS(document, { alphabetize: true, exportType: true, defaultNonNullable: false });
  const header = [
    "/* eslint-disable */",
    "// GENERATED by scripts/generate.mjs from contract/openapi.json -- do not edit.",
    "// Regenerate: backend `uv run python -m scripts.export_openapi`, then",
    "// `pnpm --filter @bstockwelldev/agent-graph-sdk run generate`.",
    "",
    `/** The API contract version these types were generated from (server header X-AGB-API-Version). */`,
    `export const CONTRACT_API_VERSION = ${JSON.stringify(document.info.version)};`,
    "",
  ].join("\n");
  return `${header}\n${astToString(ast)}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const rendered = await renderGenerated();
  const outputPath = fileURLToPath(outputUrl);
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(outputPath, "utf8");
    } catch {}
    if (current !== rendered) {
      console.error("src/generated/openapi.ts is stale; run `pnpm --filter @bstockwelldev/agent-graph-sdk run generate`");
      process.exit(1);
    }
    console.log("src/generated/openapi.ts is up to date");
  } else {
    writeFileSync(outputPath, rendered);
    console.log(`wrote ${outputPath}`);
  }
}
